version: "3"
services:
  db:
    image: 'mariadb'
    volumes:
      - './data/mysql:/var/lib/mysql'
    ports:
      - 18001:3306
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
  webserver:
    depends_on:
      - db
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./src:/var/www/html"
      - "./docker/site.conf:/etc/nginx/conf.d/default.conf"
  php:
    build:
      context: .
    volumes:
      - "./src:/var/www/html"
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
  phpmyadmin:
    image: corbinu/docker-phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: my_user
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_PORT_3306_TCP_ADDR: db
